### ISSUE TITLE
setRequired doesn't guarantee valid date

### ISSUE THREAD

**Issue by janlanger** [nella/forms-datetime#2]
Adding `setRequired` to field do not guarantee that value will be valid, because isFilled method checks only if any value was sent. This causes that required field can return `null` after submit...

Try setting `21.4.2015` (no spaces) to `DateInput` :)

**Comment by janlanger** [comment]
BTW, it could be more graceful in accepted formats (like the mentioned 21.4.2015)

**Comment by Vrtak-CZ** [comment]
@janlanger please add second issue for "spaces". I probably solve it at Friday.

**Comment by Vrtak-CZ** [comment]
implemented https://github.com/nella/forms-datetime/commit/e7afe1d2e5355f7f7f8b44949451460cf249a224
